version: "3.9"
service:
  client:
    container_name: client
    restart: always
    build: ./client
    ports: 
      - "3000/3000"
    links: 
      - app
  app: 
    container_name: app
    restart: always
    build: ./api 
    ports: 
      - "4000:4000"
    depends_on: 
      - mongo
    mongo: 
        container_name: mongo
        image: mongo
        restart: always
        expose:
          - "27017"
        volumes: 
          - ./data:/data/db
        ports: 
          - "27017:27017"

#for mongos db you are able to link both the mongo contaitor to other containor. This is the basics on how to link containor to each other. On top of this a .YML file is needed to specificy how you want to compose your docker file. 

#docker-compose up -d and the name of the service in this its mongo. This allows you to run certain commands in the propper order
# Docker logs id number to look at the logs for induvisual container 
# can also be done in the docker desktop app
#Docker-compose stop to kill all of the containors
      